export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";

export const ORDER_GET_REQUEST = "ORDER_GET_REQUEST";
export const ORDER_GET_SUCCESS = "ORDER_GET_SUCCESS";
export const ORDER_GET_FAIL = "ORDER_GET_FAIL";
export const ORDER_GET_RESET = "ORDER_GET_RESET";

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const ORDERS_GET_REQUEST = "ORDERS_GET_REQUEST";
export const ORDERS_GET_SUCCESS = "ORDERS_GET_SUCCESS";
export const ORDERS_GET_FAIL = "ORDERS_GET_FAIL";

export const ORDERS_ADMIN_GET_REQUEST = "ORDERS_ADMIN_GET_REQUEST";
export const ORDERS_ADMIN_GET_SUCCESS = "ORDERS_ADMIN_GET_SUCCESS";
export const ORDERS_ADMIN_GET_FAIL = "ORDERS_ADMIN_GET_FAIL";

export const ORDER_ADMIN_UPDATE_DELIVER_REQUEST =
  "ORDER_ADMIN_UPDATE_DELIVER_REQUEST";
export const ORDER_ADMIN_UPDATE_DELIVER_SUCCESS =
  "ORDER_ADMIN_UPDATE_DELIVER_SUCCESS";
export const ORDER_ADMIN_UPDATE_DELIVER_FAIL =
  "ORDER_ADMIN_UPDATE_DELIVER_FAIL";
export const ORDER_ADMIN_UPDATE_DELIVER_RESET =
  "ORDER_ADMIN_UPDATE_DELIVER_RESET";
